### ISSUE TITLE
Docs show incorrect listener

### ISSUE THREAD

**Issue by jolora** [SocialiteProviders/deviantART#2]
Should show:
`'SocialiteProviders\Deviantart\DeviantartExtendSocialite@handle',`

instead of:
`'SocialiteProviders\Deviantart\DeviantArtExtendSocialite@handle',`

**Comment by DraperStudio** [comment]
https://github.com/SocialiteProviders/socialiteproviders.github.io/commit/211ae3ca7b23ff2e8ffbb4d5b12391fc4a9cf9aa
